# Generated by Django 4.2.6 on 2023-11-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensajeria', '0002_remove_mensaje_id_remitente_mensaje_destinatario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
