# Generated by Django 4.2.6 on 2023-11-01 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='anio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='horas',
            field=models.IntegerField(default=2024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='instituto',
            field=models.CharField(default=2024, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='lugar',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='mes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
