# Generated by Django 4.2.6 on 2023-11-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_curso_anio_curso_horas_curso_instituto_curso_lugar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='categoria_id',
        ),
    ]
