# Generated by Django 4.2.6 on 2023-11-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_alter_curso_nombre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
