# Generated by Django 4.2.6 on 2023-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_entrada_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='id_categoria',
            field=models.IntegerField(),
        ),
    ]
