# Generated by Django 4.2.6 on 2023-11-08 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_entrada_id_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='entradas'),
        ),
    ]
