# Generated by Django 4.2.6 on 2023-11-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_entrada_imagen_portada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='id_categoria',
        ),
    ]
