# Generated by Django 4.2.6 on 2023-11-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_entrada_imagen_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='id_categoria',
            field=models.IntegerField(default=1),
        ),
    ]
