# Generated by Django 4.2.6 on 2023-11-09 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_entrada_id_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='id_categoria',
        ),
    ]
