# Generated by Django 4.2.6 on 2023-11-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_entrada_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='id_categoria',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entrada',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='entradas'),
        ),
    ]
