# Generated by Django 4.2.6 on 2023-11-09 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_entrada_id_categoria_alter_entrada_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='id_categoria',
            field=models.IntegerField(default=1),
        ),
    ]
