# Generated by Django 4.2.6 on 2023-11-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_entrada_id_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='id_categoria',
        ),
    ]
