# Generated by Django 4.2.6 on 2023-11-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_entrada_categoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='id_autor',
            field=models.IntegerField(null=True),
        ),
    ]
