# Generated by Django 4.2.6 on 2023-11-10 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_entrada_id_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='id_categoria',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria'),
        ),
    ]
